site_name: Assembly and annotation course
nav:
    - Home: index.md
    - Course schedule: course_schedule.md
    - Exercises: 
      - Assembly: 
        - Week 1 - reads & QC: Assembly/week1.md
        - Week 2 - assembly: Assembly/week2.md
        - Week 3 - assembly evaluation: Assembly/week3.md
        - Week 4 - comparing genomes: Assembly/week4.md
      - Annotation:
        - Week 5: Annotation/week5.md

theme:
  name: material

# Repository
repo_name: GeertvanGeest/assembly-annotation-course
repo_url: https://GeertvanGeest.github.io/assembly-annotation-course/

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
